### ISSUE TITLE
nbcompose connect to noteblock

### ISSUE THREAD

**Issue by ask-compu** [20kdc/OC-KittenOS#3]
how do i connect nbcompose to noteblocks? the ones i use in openos seem to not work with nbcompose on kittenos

**Comment by 20kdc** [comment]
Which kinds of noteblocks? Specific mod details, etc. They might be a different kind I have to add support for.

**Comment by ask-compu** [comment]
i figured it out, the program requires iron note blocks from a mode, not a standard noteblack connected via an adapter that the midi program can use

**Comment by 20kdc** [comment]
Looked at the noteblocks in question, and while they might be able to support more instruments than the iron note block they'll require a bunch of channel configuration in response. Hmm.

**Comment by ask-compu** [comment]
i just added the computronics mod and connected an iron note block and the program worked fine, i'm not sure u can do it with standard note blocks as the computer can't change the note block's instrument, it can only do that with iron note blocks

**Comment by 20kdc** [comment]
That's where the "bunch of channel configuration" comes in... multiple noteblocks, one per instrument

**Comment by ask-compu** [comment]
alright

**Comment by 20kdc** [comment]
...nvm, looking closely it takes a whole tick to trigger one of these. The problem with this being that it'll totally screw up timing.
So I'm closing this on the basis that nbcompose will just work with Iron Note Blocks unless reason is given that one-note-per-tick is a non-issue.
