### ISSUE TITLE
Problem with license

### ISSUE THREAD

**Issue by ghost** [20kdc/OC-KittenOS#5]
In many European countries, it's __not__ possible to voluntarily dedicate code into the public domain. It would be nice if you replaced it with or add an alternative all-permissive license, such as [this one](https://en.wikipedia.org/wiki/BSD_licenses#0-clause_license_(%22Zero_Clause_BSD%22)).

**Comment by 20kdc** [comment]
That might actually work for my purposes. I needed something equivalent to CC0 but that wouldn't bloat the filesize too heavily.

**Comment by 20kdc** [comment]
```
Copyright (C) 2018-2021 by KittenOS NEO contributors

Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
THIS SOFTWARE.
```
Is this suitable?

**Comment by ghost** [comment]
It should be fine

**Comment by 20kdc** [comment]
Please see latest release.
